"""Generate the paper's LaTeX tables directly from raw measured logs.

Reads experiments/<run>/run.json and trial_*.json, reuses the per-trial
metrics in analysis/analyze.py, and writes:

  paper/tables/anomalies.tex  one row per (engine, strategy, temperature)
  paper/tables/latency.tex    restart and recovery latency per engine
  paper/tables/env.tex        engine/library versions and GPU per engine
  paper/tables/provenance.tex runs, trials, commits, exclusions

No number is typed by hand: re-running this script on the committed logs
reproduces every table. Runs whose two failure-free references disagree
are excluded from the anomaly table (divergence is not interpretable for
them) and counted in provenance.tex.

    python analysis/make_tables.py            # reads experiments/
    python analysis/make_tables.py --root X   # any directory of runs
"""
import argparse
import glob
import json
import os
import statistics
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from analyze import analyze_trial  # noqa: E402

ENGINE_NAME = {"vllm": "vLLM", "sglang": "SGLang", "llamacpp": "llama.cpp"}
STRATEGY_NAME = {"naive_retry": "naive", "recompute": "recomp."}


def tex(s):
    return (str(s).replace("\\", r"\textbackslash{}").replace("_", r"\_")
            .replace("%", r"\%").replace("&", r"\&").replace("#", r"\#"))


def frac(k, n):
    return f"{k}/{n}" if n else "--"


def med_range(xs):
    xs = [x for x in xs if x is not None]
    if not xs:
        return "--"
    return f"{statistics.median(xs):.1f} ({min(xs):.1f}--{max(xs):.1f})"


def load_runs(root):
    runs = []
    for run_path in sorted(glob.glob(os.path.join(root, "*", "run.json"))):
        with open(run_path, encoding="utf-8") as f:
            run = json.load(f)
        if run.get("run_type") != "measured":
            continue  # smoke runs are never reported
        ref = run["reference"]["text"]
        trials = []
        for t in sorted(glob.glob(os.path.join(os.path.dirname(run_path), "trial_*.json"))):
            with open(t, encoding="utf-8") as f:
                trials.append(analyze_trial(json.load(f), ref))
        runs.append((run, trials))
    return runs


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--root", default="experiments")
    p.add_argument("--out", default=os.path.join("paper", "tables"))
    a = p.parse_args()

    runs = load_runs(a.root)
    if not runs:
        sys.exit(f"no measured runs under {a.root}/; nothing written")
    os.makedirs(a.out, exist_ok=True)

    cells = defaultdict(list)          # (engine, strategy, temp) -> trial rows
    excluded = defaultdict(int)        # same key -> excluded trials
    lat = defaultdict(lambda: {"restart": [], "recovery": []})
    env_by_engine = {}
    commits = set()
    n_trials = 0

    for run, trials in runs:
        cfg = run["config"]
        key = (run["engine"], cfg["strategy"], float(cfg["temperature"]))
        commits.add(str(run["environment"].get("git_commit"))[:7])
        n_trials += len(trials)
        if run["reference_repeat_identical"]:
            cells[key].extend(trials)
        else:
            excluded[key] += len(trials)
        for t in trials:
            lat[run["engine"]]["restart"].append(t["restart_s"])
            lat[run["engine"]]["recovery"].append(t["recovery_latency_s"])
        env_by_engine.setdefault(run["engine"], run["environment"])

    # anomalies
    rows = []
    for key in sorted(set(cells) | set(excluded)):
        eng, strat, temp = key
        ts = cells.get(key, [])
        n = len(ts)
        exact = sum(t["exact_match"] for t in ts)
        full = sum(t["duplicated_fraction"] == 1.0 for t in ts)
        div = sum(t["diverged_after_dedup"] for t in ts)
        note = f" ({excluded[key]} excl.)" if excluded.get(key) else ""
        rows.append(f"{ENGINE_NAME.get(eng, tex(eng))} & {STRATEGY_NAME.get(strat, tex(strat))} & "
                    f"{temp:g} & {frac(exact, n)} & {frac(full, n)} & {frac(div, n)}{note} \\\\")
    with open(os.path.join(a.out, "anomalies.tex"), "w", encoding="utf-8") as f:
        f.write("% generated by analysis/make_tables.py; do not edit by hand\n")
        f.write("\n".join(rows) + "\n")

    # latency
    with open(os.path.join(a.out, "latency.tex"), "w", encoding="utf-8") as f:
        f.write("% generated by analysis/make_tables.py; do not edit by hand\n")
        for eng in sorted(lat):
            f.write(f"{ENGINE_NAME.get(eng, tex(eng))} & {med_range(lat[eng]['restart'])} & "
                    f"{med_range(lat[eng]['recovery'])} \\\\\n")

    # environment
    with open(os.path.join(a.out, "env.tex"), "w", encoding="utf-8") as f:
        f.write("% generated by analysis/make_tables.py; do not edit by hand\n")
        for eng in sorted(env_by_engine):
            e = env_by_engine[eng]
            pk = e.get("packages", {})
            gpus = e.get("gpus") or []
            gpu = f"{gpus[0]['name']} ({gpus[0]['memory_total']}), driver {gpus[0]['driver']}" if gpus else "none recorded"
            ver = pk.get(eng) or "n/a"
            f.write(f"{ENGINE_NAME.get(eng, tex(eng))} & {tex(ver)} & {tex(pk.get('torch') or 'n/a')} & "
                    f"{tex(gpu)} \\\\\n")

    # provenance summary
    with open(os.path.join(a.out, "provenance.tex"), "w", encoding="utf-8") as f:
        f.write("% generated by analysis/make_tables.py; do not edit by hand\n")
        f.write(f"{len(runs)} measured runs, {n_trials} trials, harness commit(s) "
                f"\\texttt{{{tex(', '.join(sorted(commits)))}}}; "
                f"{sum(excluded.values())} trials excluded because their failure-free "
                f"references disagreed.\n")

    print(f"wrote {len(rows)} anomaly rows, {len(lat)} latency rows to {a.out}/")


if __name__ == "__main__":
    main()
